---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.1
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'

  flowise:
    image: flowiseai/flowise:${FLOWISE_VERSION:-3.0.8}
    container_name: flowise
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME:-admin}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD:-admin123}
      - DATABASE_PATH=${DATABASE_PATH:-/root/.flowise}
      - APIKEY_PATH=${APIKEY_PATH:-/root/.flowise}
      - SECRETKEY_PATH=${SECRETKEY_PATH:-/root/.flowise}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_PATH=${LOG_PATH:-/root/.flowise/logs}
    volumes:
      - ./flowise_data:/root/.flowise
    networks:
      - flowise_network
    # depends_on:
    #   weaviate:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flowise_network:
    driver: bridge